---
title: "Accidents in Berlin, 2019"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(sf)
library(tidyverse)
library(tmap)
```

Interactive Gallery
==========

Row {data-width=500}
-----------------------------------------------------------------------

###  Berlin Accident Locations

```{r include = FALSE}
# 2019 accident data
raw_unfaelle <- read_csv2("unfaelle.csv", locale=locale(encoding="latin1"))

# Create sf object from X/Y coord columns. Lon/Lat is EPSG:4326
unfaelle <- st_as_sf(raw_unfaelle, coords=c("XGCSWGS84","YGCSWGS84"), crs=4326)

# Berlin neighborhoods
bezirke <- st_read("shp-bezirke/bezirke_berlin.shp")

# Base map
# basemap <- read_osm(bezirke, ext=1.1)

# 1. Plot the dots themselves
tmap_mode("view") # tmap_mode("plot")
#tm_basemap("OpenStreetMap.DE") +

unfaelle <- mutate(unfaelle, bike_related=IstRad==1)

```


```{r}
tm_shape(bezirke) +
  tm_polygons() +
  tm_shape(unfaelle) +
  tm_dots(size=0.01, col="bike_related", title="2019 Accidents: Bike-related?")

```

Source Data: <www.google.com>

### Collisions by Neighborhood


```{r include=FALSE}
unfaelle <- st_transform(unfaelle, crs = 25833)
bezirke <- st_transform(bezirke, crs = 25833)

joined_data <- st_join(bezirke, unfaelle["IstRad"])

accident_summary <- joined_data %>%
  group_by(SCHLUESSEL) %>%
  summarize(num_accidents=n())

```

```{r}
tm_shape(bezirke) +
  tm_polygons() +
  tm_shape(accident_summary) +
  tm_dots(size="num_accidents", col = "num_accidents", title="Collisions by Neighborhood, 2019")

```

Row {data-width=200}
-----------------------------------------------------------------------




### Neighborhood Summary Data

```{r}

knitr::kable(accident_summary)

```

Discussion
==========

The data stems from the following....


## disc1


dsfajhkdsfl

## disc2

dasfadsfasdf
